### ISSUE TITLE
Download options truncates long names

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-portal#181]
Long dataset names are truncated in the Download Options box, which makes download commands invalid. For instance, for dataset `MRI_and_unbiased_averages_of_wild_muskrats__Ondatra_zibethicus__and_red_squirrels__Tamiasciurus_hudsonicus_`:

![Screenshot from 2020-02-29 16-12-27](https://user-images.githubusercontent.com/5174953/75615171-8eb33380-5b0e-11ea-9804-0bd68d79f64c.png)

**Comment by liamocn** [comment]
This has been resolved

**Comment by cmadjar** [comment]
I just looked at the portal and I still see an issue about this (see screenshot). Does that mean that the portal needs to be updated?

![Screen Shot 2020-04-02 at 9 16 41 AM](https://user-images.githubusercontent.com/1402456/78253852-0a641f80-74c3-11ea-83ac-e5e5f23458f8.png)

**Comment by liamocn** [comment]
Here's what it looks like for me on my local machine

![download_options](https://user-images.githubusercontent.com/8952928/78254578-20261480-74c4-11ea-9a8a-1c4bfba3c1f1.png)

This code is already deployed to portal.conp.ca, so it's not being caused by the views. Maybe this is an issue with the 'dataset_id' field in the prod database?
